const FORTNITE_SPRITE_DATABASE = [    { id: "13_duck", num: 13, name: "Duck", rarity: "epic", exp: 10, color: "#9333EA", file: "sprites/epic/13_Duck.webp" },
    { id: "17_ghost", num: 17, name: "Ghost", rarity: "epic", exp: 10, color: "#9333EA", file: "sprites/epic/17_Ghost.webp" },
    { id: "29_king", num: 29, name: "King", rarity: "epic", exp: 10, color: "#9333EA", file: "sprites/epic/29_King.webp" },
    { id: "37_demon", num: 37, name: "Demon", rarity: "epic", exp: 10, color: "#9333EA", file: "sprites/epic/37_Demon.webp" },
    { id: "62_striker", num: 62, name: "Striker", rarity: "epic", exp: 10, color: "#9333EA", file: "sprites/epic/62_Striker.webp" },
    { id: "67_aura", num: 67, name: "Aura", rarity: "epic", exp: 10, color: "#9333EA", file: "sprites/epic/67_Aura.webp" },
    { id: "151_llama", num: 151, name: "Llama", rarity: "legendary", exp: 20, color: "#EAB308", file: "sprites/legendary/151_Llama.webp" },
    { id: "156_peely", num: 156, name: "Peely", rarity: "legendary", exp: 20, color: "#EAB308", file: "sprites/legendary/156_Peely.webp" },
    { id: "21_dream", num: 21, name: "Dream", rarity: "legendary", exp: 20, color: "#EAB308", file: "sprites/legendary/21_Dream.webp" },
    { id: "25_punk", num: 25, name: "Punk", rarity: "legendary", exp: 20, color: "#EAB308", file: "sprites/legendary/25_Punk.webp" },
    { id: "49_boss", num: 49, name: "Boss", rarity: "legendary", exp: 20, color: "#EAB308", file: "sprites/legendary/49_Boss.webp" },
    { id: "53_seven", num: 53, name: "Seven", rarity: "legendary", exp: 20, color: "#EAB308", file: "sprites/legendary/53_Seven.webp" },
    { id: "138_john_wick", num: 138, name: "John Wick", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/138_John Wick.webp" },
    { id: "139_batman", num: 139, name: "Batman", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/139_Batman.webp" },
    { id: "148_pollo", num: 148, name: "Pollo", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/148_Pollo.webp" },
    { id: "149_vini_jr_", num: 149, name: "Vini Jr.", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/149_Vini Jr..webp" },
    { id: "150_ironmouse", num: 150, name: "Ironmouse", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/150_Ironmouse.webp" },
    { id: "33_zero_point", num: 33, name: "Zero Point", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/33_Zero Point.webp" },
    { id: "41_burnt_peanut", num: 41, name: "Burnt Peanut", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/41_Burnt Peanut.webp" },
    { id: "78_grim", num: 78, name: "Grim", rarity: "mythic", exp: 50, color: "#EF4444", file: "sprites/mythic/78_Grim.webp" },
    { id: "1_water", num: 1, name: "Water", rarity: "rare", exp: 5, color: "#2176FF", file: "sprites/rare/1_Water.webp" },
    { id: "58_fishy", num: 58, name: "Fishy", rarity: "rare", exp: 5, color: "#2176FF", file: "sprites/rare/58_Fishy.webp" },
    { id: "5_earth", num: 5, name: "Earth", rarity: "rare", exp: 5, color: "#2176FF", file: "sprites/rare/5_Earth.webp" },
    { id: "74_air", num: 74, name: "Air", rarity: "rare", exp: 5, color: "#2176FF", file: "sprites/rare/74_Air.webp" },
    { id: "9_fire", num: 9, name: "Fire", rarity: "rare", exp: 5, color: "#2176FF", file: "sprites/rare/9_Fire.webp" },
    { id: "104_gem_punk", num: 104, name: "Gem Punk", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/104_Gem Punk.webp" },
    { id: "106_cube_punk", num: 106, name: "Cube Punk", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/106_Cube Punk.webp" },
    { id: "10_gummy_fire", num: 10, name: "Gummy Fire", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/10_Gummy Fire.webp" },
    { id: "111_holofoil_zero_point", num: 111, name: "Holofoil Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/111_Holofoil Zero Point.webp" },
    { id: "112_cube_zero_point", num: 112, name: "Cube Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/112_Cube Zero Point.webp" },
    { id: "113_quack_zero_point", num: 113, name: "Quack Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/113_Quack Zero Point.webp" },
    { id: "116_cube_fishy", num: 116, name: "Cube Fishy", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/116_Cube Fishy.webp" },
    { id: "11_galaxy_fire", num: 11, name: "Galaxy Fire", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/11_Galaxy Fire.webp" },
    { id: "126_cube_boss", num: 126, name: "Cube Boss", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/126_Cube Boss.webp" },
    { id: "128_gem_grim", num: 128, name: "Gem Grim", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/128_Gem Grim.webp" },
    { id: "129_holofoil_grim", num: 129, name: "Holofoil Grim", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/129_Holofoil Grim.webp" },
    { id: "12_gold_fire", num: 12, name: "Gold Fire", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/12_Gold Fire.webp" },
    { id: "130_cube_grim", num: 130, name: "Cube Grim", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/130_Cube Grim.webp" },
    { id: "140_gold_batman", num: 140, name: "Gold Batman", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/140_Gold Batman.webp" },
    { id: "141_gummy_batman", num: 141, name: "Gummy Batman", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/141_Gummy Batman.webp" },
    { id: "142_galaxy_batman", num: 142, name: "Galaxy Batman", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/142_Galaxy Batman.webp" },
    { id: "145_holofoil_batman", num: 145, name: "Holofoil Batman", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/145_Holofoil Batman.webp" },
    { id: "146_cube_batman", num: 146, name: "Cube Batman", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/146_Cube Batman.webp" },
    { id: "14_gummy_duck", num: 14, name: "Gummy Duck", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/14_Gummy Duck.webp" },
    { id: "152_gold_llama", num: 152, name: "Gold Llama", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/152_Gold Llama.webp" },
    { id: "153_gummy_llama", num: 153, name: "Gummy Llama", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/153_Gummy Llama.webp" },
    { id: "154_galaxy_llama", num: 154, name: "Galaxy Llama", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/154_Galaxy Llama.webp" },
    { id: "155_gem_llama", num: 155, name: "Gem Llama", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/155_Gem Llama.webp" },
    { id: "157_gold_peely", num: 157, name: "Gold Peely", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/157_Gold Peely.webp" },
    { id: "158_gummy_peely", num: 158, name: "Gummy Peely", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/158_Gummy Peely.webp" },
    { id: "159_galaxy_peely", num: 159, name: "Galaxy Peely", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/159_Galaxy Peely.webp" },
    { id: "15_galaxy_duck", num: 15, name: "Galaxy Duck", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/15_Galaxy Duck.webp" },
    { id: "160_holofoil_peely", num: 160, name: "Holofoil Peely", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/160_Holofoil Peely.webp" },
    { id: "16_gold_duck", num: 16, name: "Gold Duck", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/16_Gold Duck.webp" },
    { id: "18_gummy_ghost", num: 18, name: "Gummy Ghost", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/18_Gummy Ghost.webp" },
    { id: "19_galaxy_ghost", num: 19, name: "Galaxy Ghost", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/19_Galaxy Ghost.webp" },
    { id: "20_gold_ghost", num: 20, name: "Gold Ghost", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/20_Gold Ghost.webp" },
    { id: "22_gummy_dream", num: 22, name: "Gummy Dream", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/22_Gummy Dream.webp" },
    { id: "23_galaxy_dream", num: 23, name: "Galaxy Dream", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/23_Galaxy Dream.webp" },
    { id: "24_gold_dream", num: 24, name: "Gold Dream", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/24_Gold Dream.webp" },
    { id: "26_gummy_punk", num: 26, name: "Gummy Punk", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/26_Gummy Punk.webp" },
    { id: "27_galaxy_punk", num: 27, name: "Galaxy Punk", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/27_Galaxy Punk.webp" },
    { id: "28_gold_punk", num: 28, name: "Gold Punk", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/28_Gold Punk.webp" },
    { id: "2_gummy_water", num: 2, name: "Gummy Water", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/2_Gummy Water.webp" },
    { id: "30_gummy_king", num: 30, name: "Gummy King", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/30_Gummy King.webp" },
    { id: "31_galaxy_king", num: 31, name: "Galaxy King", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/31_Galaxy King.webp" },
    { id: "32_gold_king", num: 32, name: "Gold King", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/32_Gold King.webp" },
    { id: "34_gummy_zero_point", num: 34, name: "Gummy Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/34_Gummy Zero Point.webp" },
    { id: "35_galaxy_zero_point", num: 35, name: "Galaxy Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/35_Galaxy Zero Point.webp" },
    { id: "36_gold_zero_point", num: 36, name: "Gold Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/36_Gold Zero Point.webp" },
    { id: "38_gummy_demon", num: 38, name: "Gummy Demon", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/38_Gummy Demon.webp" },
    { id: "39_galaxy_demon", num: 39, name: "Galaxy Demon", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/39_Galaxy Demon.webp" },
    { id: "3_galaxy_water", num: 3, name: "Galaxy Water", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/3_Galaxy Water.webp" },
    { id: "40_gold_demon", num: 40, name: "Gold Demon", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/40_Gold Demon.webp" },
    { id: "42_gold_air", num: 42, name: "Gold Air", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/42_Gold Air.webp" },
    { id: "43_holofoil_water", num: 43, name: "Holofoil Water", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/43_Holofoil Water.webp" },
    { id: "44_gem_duck", num: 44, name: "Gem Duck", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/44_Gem Duck.webp" },
    { id: "45_gem_earth", num: 45, name: "Gem Earth", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/45_Gem Earth.webp" },
    { id: "46_holofoil_fire", num: 46, name: "Holofoil Fire", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/46_Holofoil Fire.webp" },
    { id: "47_gem_demon", num: 47, name: "Gem Demon", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/47_Gem Demon.webp" },
    { id: "48_holofoil_ghost", num: 48, name: "Holofoil Ghost", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/48_Holofoil Ghost.webp" },
    { id: "4_gold_water", num: 4, name: "Gold Water", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/4_Gold Water.webp" },
    { id: "50_gold_boss", num: 50, name: "Gold Boss", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/50_Gold Boss.webp" },
    { id: "51_gummy_boss", num: 51, name: "Gummy Boss", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/51_Gummy Boss.webp" },
    { id: "52_galaxy_boss", num: 52, name: "Galaxy Boss", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/52_Galaxy Boss.webp" },
    { id: "54_gummy_seven", num: 54, name: "Gummy Seven", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/54_Gummy Seven.webp" },
    { id: "55_galaxy_seven", num: 55, name: "Galaxy Seven", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/55_Galaxy Seven.webp" },
    { id: "56_gold_seven", num: 56, name: "Gold Seven", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/56_Gold Seven.webp" },
    { id: "57_holofoil_seven", num: 57, name: "Holofoil Seven", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/57_Holofoil Seven.webp" },
    { id: "59_gummy_fishy", num: 59, name: "Gummy Fishy", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/59_Gummy Fishy.webp" },
    { id: "60_galaxy_fishy", num: 60, name: "Galaxy Fishy", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/60_Galaxy Fishy.webp" },
    { id: "61_gold_fishy", num: 61, name: "Gold Fishy", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/61_Gold Fishy.webp" },
    { id: "63_gummy_striker", num: 63, name: "Gummy Striker", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/63_Gummy Striker.webp" },
    { id: "64_galaxy_striker", num: 64, name: "Galaxy Striker", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/64_Galaxy Striker.webp" },
    { id: "65_gold_striker", num: 65, name: "Gold Striker", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/65_Gold Striker.webp" },
    { id: "66_holofoil_striker", num: 66, name: "Holofoil Striker", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/66_Holofoil Striker.webp" },
    { id: "68_gummy_aura", num: 68, name: "Gummy Aura", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/68_Gummy Aura.webp" },
    { id: "69_galaxy_aura", num: 69, name: "Galaxy Aura", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/69_Galaxy Aura.webp" },
    { id: "6_gummy_earth", num: 6, name: "Gummy Earth", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/6_Gummy Earth.webp" },
    { id: "70_gem_aura", num: 70, name: "Gem Aura", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/70_Gem Aura.webp" },
    { id: "71_gold_aura", num: 71, name: "Gold Aura", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/71_Gold Aura.webp" },
    { id: "72_gummy_air", num: 72, name: "Gummy Air", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/72_Gummy Air.webp" },
    { id: "73_holofoil_king", num: 73, name: "Holofoil King", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/73_Holofoil King.webp" },
    { id: "75_galaxy_air", num: 75, name: "Galaxy Air", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/75_Galaxy Air.webp" },
    { id: "76_gem_water", num: 76, name: "Gem Water", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/76_Gem Water.webp" },
    { id: "77_holofoil_air", num: 77, name: "Holofoil Air", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/77_Holofoil Air.webp" },
    { id: "79_gummy_grim", num: 79, name: "Gummy Grim", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/79_Gummy Grim.webp" },
    { id: "7_galaxy_earth", num: 7, name: "Galaxy Earth", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/7_Galaxy Earth.webp" },
    { id: "80_galaxy_grim", num: 80, name: "Galaxy Grim", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/80_Galaxy Grim.webp" },
    { id: "81_gold_grim", num: 81, name: "Gold Grim", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/81_Gold Grim.webp" },
    { id: "82_gem_zero_point", num: 82, name: "Gem Zero Point", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/82_Gem Zero Point.webp" },
    { id: "84_quack_water", num: 84, name: "Quack Water", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/84_Quack Water.webp" },
    { id: "86_cube_earth", num: 86, name: "Cube Earth", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/86_Cube Earth.webp" },
    { id: "87_quack_earth", num: 87, name: "Quack Earth", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/87_Quack Earth.webp" },
    { id: "89_cube_fire", num: 89, name: "Cube Fire", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/89_Cube Fire.webp" },
    { id: "8_gold_earth", num: 8, name: "Gold Earth", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/8_Gold Earth.webp" },
    { id: "90_quack_fire", num: 90, name: "Quack Fire", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/90_Quack Fire.webp" },
    { id: "99_cube_dream", num: 99, name: "Cube Dream", rarity: "special", exp: 35, color: "#EC4899", file: "sprites/special/99_Cube Dream.webp" }
];
